### ISSUE TITLE
No module named 'abpytools.core.formats.chain_pb2'

### ISSUE THREAD

**Issue by m-abyzov** [gf712/AbPyTools#7]
getting this error during install via pip or source:

======================================================================
ERROR: features_tests_composition (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: features_tests_composition
Traceback (most recent call last):
  File "/home/misha/anaconda3/lib/python3.7/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/home/misha/internship_code/AbPyTools/tests/features_tests_composition.py", line 2, in <module>
    from abpytools import ChainCollection
  File "/home/misha/internship_code/AbPyTools/abpytools/__init__.py", line 1, in <module>
    from .core import *
  File "/home/misha/internship_code/AbPyTools/abpytools/core/__init__.py", line 4, in <module>
    from .chain_collection import ChainCollection
  File "/home/misha/internship_code/AbPyTools/abpytools/core/chain_collection.py", line 18, in <module>
    from .utils import (json_ChainCollection_formatter, pb2_ChainCollection_formatter, pb2_ChainCollection_parser,
  File "/home/misha/internship_code/AbPyTools/abpytools/core/utils.py", line 1, in <module>
    from abpytools.core.formats.utils import get_protobuf_numbering_scheme, get_numbering_scheme_from_protobuf
  File "/home/misha/internship_code/AbPyTools/abpytools/core/formats/__init__.py", line 1, in <module>
    from .chain_pb2 import Chain as ChainProto
ModuleNotFoundError: No module named 'abpytools.core.formats.chain_pb2'

**Comment by merkys** [comment]
This happens when protobuf is not installed. I had to install `protobuf` Python package and protoc compiler. On Debian I had to install `python3-protobuf` and `protobuf-compiler` packages.
